Dns info
elementary/switchboard-plug-network pull request #276
Opened 2020-09-06 08:35 UTC by bastinc

Add DNS addresses in InfoBox

2020-09-22 21:44 UTC, cassidyjames requested changes
When I change DNS settings for a network, this doesn't appear to be reflected here; it continues to show my router's IP address, instead.

2020-09-24 16:31 UTC, bastinc commented
@cassidyjames did you restart the network connection ? It's needed for changes to take effect and to be reflected in the info box.

![Capture d’écran de 2020-09-24 18-25-20](https://user-images.githubusercontent.com/5850561/94173263-fa3a6500-fe93-11ea-96e7-4e8ef729f1be.png)
![Capture d’écran de 2020-09-24 18-25-40](https://user-images.githubusercontent.com/5850561/94173275-fd355580-fe93-11ea-8cd2-0fa13d56e2a0.png)

2021-06-04 15:14 UTC, jeremypw commented on src/Widgets/InfoBox.vala
> +
The preferred way of initializing objects is now:
```
var obj = new Object (<params>) {
    prop1 = val1,
    ....
    propx = valx
};
```

2021-06-04 16:02 UTC, jeremypw approved these changes
Minor code style issue but as the rest of the code does not comply probably can be fixed when the code is all updated.

A changed in DNS setting is not reflected in the popover until the connection is broken and re-established but that is not caused by this PR and there is no simple way of changing this behaviour afaict.

2021-06-04 16:04 UTC, merged