fix reconnecting while set switchbutton to unactive
elementary/switchboard-plug-network pull request #328
Opened 2021-11-26 09:47 UTC by anzyelay

to resolve  "Network settings panel keeps reconnecting wired network #326 "

2021-12-09 19:10 UTC, jeremypw requested changes
This successfully stabilises the Ethernet reconnection under circumstances described in
#326 and #312 - thanks for the fix!

Just a comment about Elementary code style.  Also although the switch statement seems to cover all possible cases, it is generally good practice to include a fallback `default:` case, even if it is only `assert_not_reached ()`.

Also please remove the commented out code.

2021-12-09 19:10 UTC, jeremypw commented on src/Widgets/Page.vala
> +                return;
Elementary codestyle:
```suggestion
            if (switch_updating) {
                return;
            }
```

2021-12-14 01:47 UTC, anzyelay commented on src/Widgets/Page.vala
> +                return;
fix elementary code style

2021-12-14 09:44 UTC, jeremypw approved these changes

2021-12-14 09:44 UTC, merged

2021-12-14 13:34 UTC, Mepth commented
Like!